import { modelTokenCounterSlug } from "@/lib/seo/slugs";
import type { ModelEntry } from "./types";

const GEMINI_PRICING_URL = "https://ai.google.dev/gemini-api/docs/pricing";

export const GEMINI_MODELS: ModelEntry[] = [
  {
    provider: "google",
    id: "gemini-3.1-pro-preview",
    name: "Gemini 3.1 Pro Preview",
    slug: modelTokenCounterSlug("gemini-3-1-pro-preview"),
    pricingBands: [
      { maxInputTokens: 200_000, inputPer1M: 2.0, cachedInputPer1M: 0.20, outputPer1M: 12.0 },
      { inputPer1M: 4.0, cachedInputPer1M: 0.40, outputPer1M: 18.0 },
    ],
    officialSourceUrl: GEMINI_PRICING_URL,
    lastVerified: "2026-02-22",
    status: "active",
    contextWindow: "2,000,000",
    notes: "Latest performance improvements with multimodal understanding and agentic capabilities. Includes thinking tokens in output pricing.",
  },
  {
    provider: "google",
    id: "gemini-3-pro-preview",
    name: "Gemini 3 Pro Preview",
    slug: modelTokenCounterSlug("gemini-3-pro-preview"),
    pricingBands: [
      { maxInputTokens: 200_000, inputPer1M: 2.0, cachedInputPer1M: 0.20, outputPer1M: 12.0 },
      { inputPer1M: 4.0, cachedInputPer1M: 0.40, outputPer1M: 18.0 },
    ],
    officialSourceUrl: GEMINI_PRICING_URL,
    lastVerified: "2026-02-22",
    status: "active",
    contextWindow: "2,000,000",
    notes: "Best model for multimodal understanding with powerful agentic and vibe-coding capabilities.",
  },
  {
    provider: "google",
    id: "gemini-3-flash-preview",
    name: "Gemini 3 Flash Preview",
    slug: modelTokenCounterSlug("gemini-3-flash-preview"),
    pricingBands: [{ inputPer1M: 0.50, cachedInputPer1M: 0.05, outputPer1M: 3.0 }],
    officialSourceUrl: GEMINI_PRICING_URL,
    lastVerified: "2026-02-22",
    status: "active",
    contextWindow: "1,000,000",
    notes: "Most intelligent model built for speed, combining frontier intelligence with superior search and grounding.",
  },
  {
    provider: "google",
    id: "gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    slug: modelTokenCounterSlug("gemini-2-5-pro"),
    pricingBands: [
      { maxInputTokens: 200_000, inputPer1M: 1.25, cachedInputPer1M: 0.125, outputPer1M: 10.0 },
      { inputPer1M: 2.50, cachedInputPer1M: 0.25, outputPer1M: 15.0 },
    ],
    officialSourceUrl: GEMINI_PRICING_URL,
    lastVerified: "2026-02-22",
    status: "active",
    contextWindow: "2,000,000",
    notes: "State-of-the-art multipurpose model which excels at coding and complex reasoning tasks.",
  },
  {
    provider: "google",
    id: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    slug: modelTokenCounterSlug("gemini-2-5-flash"),
    pricingBands: [{ inputPer1M: 0.30, cachedInputPer1M: 0.03, outputPer1M: 2.50 }],
    officialSourceUrl: GEMINI_PRICING_URL,
    lastVerified: "2026-02-22",
    status: "active",
    contextWindow: "1,000,000",
    notes: "First hybrid reasoning model with 1M token context window and thinking budgets. Audio input: $1.00/1M tokens.",
  },
  {
    provider: "google",
    id: "gemini-2.0-flash",
    name: "Gemini 2.0 Flash",
    slug: modelTokenCounterSlug("gemini-2-0-flash"),
    pricingBands: [{ inputPer1M: 0.10, cachedInputPer1M: 0.025, outputPer1M: 0.40 }],
    officialSourceUrl: GEMINI_PRICING_URL,
    lastVerified: "2026-02-22",
    status: "active",
    contextWindow: "1,000,000",
    notes: "Most balanced multimodal model built for the era of Agents. Audio input: $0.70/1M tokens.",
  },
];