import { modelTokenCounterSlug } from "@/lib/seo/slugs";
import type { ModelEntry } from "./types";

const META_PRICING_URL = "https://llama.meta.com/";

export const META_MODELS: ModelEntry[] = [
  {
    provider: "meta",
    id: "llama-4-maverick",
    name: "Llama 4 Maverick",
    slug: modelTokenCounterSlug("llama-4-maverick"),
    pricingBands: [{ inputPer1M: 2.0, outputPer1M: 6.0 }],
    officialSourceUrl: META_PRICING_URL,
    lastVerified: "2026-02-22",
    status: "active",
    contextWindow: "1,000,000",
    notes: "Largest Llama 4 model with 400B total parameters, optimized for multimodal understanding, multilingual tasks, and agentic systems. Requires multiple GPUs.",
  },
  {
    provider: "meta",
    id: "llama-4-scout",
    name: "Llama 4 Scout",
    slug: modelTokenCounterSlug("llama-4-scout"),
    pricingBands: [{ inputPer1M: 0.88, outputPer1M: 0.88 }],
    officialSourceUrl: META_PRICING_URL,
    lastVerified: "2026-02-22",
    status: "active",
    contextWindow: "10,000,000",
    notes: "Smaller Llama 4 model with 109B total parameters, can run on single GPU. Supports text + up to 5 images input, 10M token context.",
  },
  {
    provider: "meta",
    id: "llama-3.3-70b-instruct",
    name: "Llama 3.3 70B Instruct",
    slug: modelTokenCounterSlug("llama-3-3-70b-instruct"),
    pricingBands: [{ inputPer1M: 0.88, outputPer1M: 0.88 }],
    officialSourceUrl: META_PRICING_URL,
    lastVerified: "2026-02-22",
    status: "active",
    contextWindow: "131,072",
    notes: "Enhanced performance relative to Llama 3.1 70B, approaches Llama 3.1 405B performance for some applications. Text-only model.",
  },
  {
    provider: "meta",
    id: "llama-3-70b-instruct",
    name: "Llama 3 70B Instruct",
    slug: modelTokenCounterSlug("llama-3-70b-instruct"),
    pricingBands: [{ inputPer1M: 0.58, outputPer1M: 1.75 }],
    officialSourceUrl: META_PRICING_URL,
    lastVerified: "2026-02-22",
    status: "active",
    contextWindow: "8,192",
    notes: "Previous generation 70B model, cost-effective option via API providers like Together AI, Groq.",
  },
  {
    provider: "meta",
    id: "llama-3-8b-instruct",
    name: "Llama 3 8B Instruct",
    slug: modelTokenCounterSlug("llama-3-8b-instruct"),
    pricingBands: [{ inputPer1M: 0.05, outputPer1M: 0.25 }],
    officialSourceUrl: META_PRICING_URL,
    lastVerified: "2026-02-22",
    status: "active",
    contextWindow: "8,192",
    notes: "Smaller, faster model starting as low as $0.05/1M tokens via providers like Replicate, DeepInfra.",
  },
];