import { modelTokenCounterSlug } from "@/lib/seo/slugs";
import type { ModelEntry } from "./types";

const OPENAI_PRICING_URL = "https://developers.openai.com/api/docs/pricing/";

export const OPENAI_MODELS: ModelEntry[] = [
  {
    provider: "openai",
    id: "gpt-5.2",
    name: "GPT-5.2",
    slug: modelTokenCounterSlug("gpt-5-2"),
    pricingBands: [{ inputPer1M: 1.75, cachedInputPer1M: 0.175, outputPer1M: 14.0 }],
    officialSourceUrl: OPENAI_PRICING_URL,
    lastVerified: "2026-02-22",
    status: "active",
    contextWindow: "200,000",
    notes: "Latest flagship model with advanced capabilities.",
  },
  {
    provider: "openai",
    id: "gpt-5.1",
    name: "GPT-5.1",
    slug: modelTokenCounterSlug("gpt-5-1"),
    pricingBands: [{ inputPer1M: 1.25, cachedInputPer1M: 0.125, outputPer1M: 10.0 }],
    officialSourceUrl: OPENAI_PRICING_URL,
    lastVerified: "2026-02-22",
    status: "active",
    contextWindow: "200,000",
    notes: "High-performance model with excellent reasoning capabilities.",
  },
  {
    provider: "openai",
    id: "gpt-5",
    name: "GPT-5",
    slug: modelTokenCounterSlug("gpt-5"),
    pricingBands: [{ inputPer1M: 1.25, cachedInputPer1M: 0.125, outputPer1M: 10.0 }],
    officialSourceUrl: OPENAI_PRICING_URL,
    lastVerified: "2026-02-22",
    status: "active",
    contextWindow: "200,000",
    notes: "Flagship GPT-5 model for general use.",
  },
  {
    provider: "openai",
    id: "gpt-5-mini",
    name: "GPT-5 mini",
    slug: modelTokenCounterSlug("gpt-5-mini"),
    pricingBands: [{ inputPer1M: 0.25, cachedInputPer1M: 0.025, outputPer1M: 2.0 }],
    officialSourceUrl: OPENAI_PRICING_URL,
    lastVerified: "2026-02-22",
    status: "active",
    contextWindow: "128,000",
    notes: "Cost-effective model for high-volume applications.",
  },
  {
    provider: "openai",
    id: "gpt-5-nano",
    name: "GPT-5 nano",
    slug: modelTokenCounterSlug("gpt-5-nano"),
    pricingBands: [{ inputPer1M: 0.05, cachedInputPer1M: 0.005, outputPer1M: 0.40 }],
    officialSourceUrl: OPENAI_PRICING_URL,
    lastVerified: "2026-02-22",
    status: "active",
    contextWindow: "64,000",
    notes: "Ultra-efficient model for simple tasks and edge computing.",
  },
  {
    provider: "openai",
    id: "o3",
    name: "o3",
    slug: modelTokenCounterSlug("o3"),
    pricingBands: [{ inputPer1M: 2.0, cachedInputPer1M: 0.50, outputPer1M: 8.0 }],
    officialSourceUrl: OPENAI_PRICING_URL,
    lastVerified: "2026-02-22",
    status: "active",
    contextWindow: "128,000",
    notes: "Advanced reasoning model with enhanced problem-solving capabilities.",
  },
  {
    provider: "openai",
    id: "o3-mini",
    name: "o3-mini",
    slug: modelTokenCounterSlug("o3-mini"),
    pricingBands: [{ inputPer1M: 1.10, cachedInputPer1M: 0.55, outputPer1M: 4.40 }],
    officialSourceUrl: OPENAI_PRICING_URL,
    lastVerified: "2026-02-22",
    status: "active",
    contextWindow: "128,000",
    notes: "Efficient reasoning model for complex tasks.",
  },
  {
    provider: "openai",
    id: "gpt-4o",
    name: "GPT-4o",
    slug: modelTokenCounterSlug("gpt-4o"),
    pricingBands: [{ inputPer1M: 2.5, cachedInputPer1M: 1.25, outputPer1M: 10.0 }],
    officialSourceUrl: OPENAI_PRICING_URL,
    lastVerified: "2026-02-22",
    status: "active",
    contextWindow: "128,000",
    notes: "Previous generation flagship model, still widely used.",
  },
];