import { modelTokenCounterSlug } from "@/lib/seo/slugs";
import type { ModelEntry } from "./types";

const TOGETHER_PRICING_URL = "https://www.together.ai/pricing";

export const TOGETHER_MODELS: ModelEntry[] = [
  {
    provider: "together",
    id: "llama-4-maverick",
    name: "Llama 4 Maverick",
    slug: modelTokenCounterSlug("llama-4-maverick"),
    pricingBands: [{ inputPer1M: 0.27, outputPer1M: 0.85 }],
    officialSourceUrl: TOGETHER_PRICING_URL,
    lastVerified: "2026-02-22",
    status: "active",
    contextWindow: "1,000,000",
    notes: "Latest Llama 4 model hosted on Together AI infrastructure with enhanced capabilities.",
  },
  {
    provider: "together",
    id: "llama-3.3-70b",
    name: "Llama 3.3 70B",
    slug: modelTokenCounterSlug("llama-3-3-70b"),
    pricingBands: [{ inputPer1M: 0.88, outputPer1M: 0.88 }],
    officialSourceUrl: TOGETHER_PRICING_URL,
    lastVerified: "2026-02-22",
    status: "active",
    contextWindow: "131,072",
    notes: "Enhanced Llama 3.3 model with improved performance over Llama 3.1 70B.",
  },
  {
    provider: "together",
    id: "llama-3.1-405b",
    name: "Llama 3.1 405B",
    slug: modelTokenCounterSlug("llama-3-1-405b"),
    pricingBands: [{ inputPer1M: 3.50, outputPer1M: 3.50 }],
    officialSourceUrl: TOGETHER_PRICING_URL,
    lastVerified: "2026-02-22",
    status: "active",
    contextWindow: "131,072",
    notes: "Largest Llama 3.1 model with flagship capabilities for complex tasks.",
  },
  {
    provider: "together",
    id: "llama-3.1-70b",
    name: "Llama 3.1 70B",
    slug: modelTokenCounterSlug("llama-3-1-70b"),
    pricingBands: [{ inputPer1M: 0.88, outputPer1M: 0.88 }],
    officialSourceUrl: TOGETHER_PRICING_URL,
    lastVerified: "2026-02-22",
    status: "active",
    contextWindow: "131,072",
    notes: "Popular mid-size Llama model with excellent performance-to-cost ratio.",
  },
  {
    provider: "together",
    id: "deepseek-r1-0528",
    name: "DeepSeek-R1-0528",
    slug: modelTokenCounterSlug("deepseek-r1-0528"),
    pricingBands: [{ inputPer1M: 3.0, outputPer1M: 7.0 }],
    officialSourceUrl: TOGETHER_PRICING_URL,
    lastVerified: "2026-02-22",
    status: "active",
    contextWindow: "128,000",
    notes: "Advanced reasoning model with enhanced problem-solving capabilities.",
  },
  {
    provider: "together",
    id: "qwen3-coder-480b-a35b",
    name: "Qwen3-Coder 480B A35B",
    slug: modelTokenCounterSlug("qwen3-coder-480b-a35b"),
    pricingBands: [{ inputPer1M: 2.0, outputPer1M: 2.0 }],
    officialSourceUrl: TOGETHER_PRICING_URL,
    lastVerified: "2026-02-22",
    status: "active",
    contextWindow: "128,000",
    notes: "Large-scale coding model optimized for software development tasks.",
  },
];