import { modelTokenCounterSlug } from "@/lib/seo/slugs";
import type { ModelEntry } from "./types";

const XAI_PRICING_URL = "https://x.ai/api";

export const XAI_MODELS: ModelEntry[] = [
  {
    provider: "xai",
    id: "grok-4-1-fast-reasoning",
    name: "Grok 4.1 Fast Reasoning",
    slug: modelTokenCounterSlug("grok-4-1-fast-reasoning"),
    pricingBands: [{ inputPer1M: 0.20, outputPer1M: 0.50 }],
    officialSourceUrl: XAI_PRICING_URL,
    lastVerified: "2026-02-22",
    status: "active",
    contextWindow: "2,000,000",
    notes: "Next generation tool-calling agents with reasoning capabilities. Image input: $0.20/1M tokens.",
  },
  {
    provider: "xai",
    id: "grok-4-1-fast-non-reasoning",
    name: "Grok 4.1 Fast Non-Reasoning",
    slug: modelTokenCounterSlug("grok-4-1-fast-non-reasoning"),
    pricingBands: [{ inputPer1M: 0.20, outputPer1M: 0.50 }],
    officialSourceUrl: XAI_PRICING_URL,
    lastVerified: "2026-02-22",
    status: "active",
    contextWindow: "2,000,000",
    notes: "Next generation tool-calling agents without reasoning overhead. Image input: $0.20/1M tokens.",
  },
  {
    provider: "xai",
    id: "grok-4-fast-reasoning",
    name: "Grok 4 Fast Reasoning",
    slug: modelTokenCounterSlug("grok-4-fast-reasoning"),
    pricingBands: [{ inputPer1M: 0.20, outputPer1M: 0.50 }],
    officialSourceUrl: XAI_PRICING_URL,
    lastVerified: "2026-02-22",
    status: "active",
    contextWindow: "2,000,000",
    notes: "Cost-efficient intelligence with reasoning capabilities. Image input: $0.20/1M tokens.",
  },
  {
    provider: "xai",
    id: "grok-4",
    name: "Grok 4",
    slug: modelTokenCounterSlug("grok-4"),
    pricingBands: [{ inputPer1M: 3.0, outputPer1M: 15.0 }],
    officialSourceUrl: XAI_PRICING_URL,
    lastVerified: "2026-02-22",
    status: "active",
    contextWindow: "256,000",
    notes: "The world's best model with premium capabilities. Image input: $3.00/1M tokens.",
  },
  {
    provider: "xai",
    id: "grok-code-fast-1",
    name: "Grok Code Fast 1",
    slug: modelTokenCounterSlug("grok-code-fast-1"),
    pricingBands: [{ inputPer1M: 0.20, outputPer1M: 1.50 }],
    officialSourceUrl: XAI_PRICING_URL,
    lastVerified: "2026-02-22",
    status: "active",
    contextWindow: "256,000",
    notes: "Lightning fast reasoning model built for agentic coding applications.",
  },
];